#!/usr/bin/env bash
# Thin command dispatcher for the repository's multi-language runtime library.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck source=scripts/lib/python.sh
source "$SCRIPT_DIR/lib/python.sh"
# shellcheck source=scripts/lib/node.sh
source "$SCRIPT_DIR/lib/node.sh"
# shellcheck source=scripts/lib/rust.sh
source "$SCRIPT_DIR/lib/rust.sh"

usage() {
  cat <<'EOF'
Usage:
  manage-runtime.sh inspect [options]
  manage-runtime.sh init [options]
  manage-runtime.sh attach-python [options]
  manage-runtime.sh validate [options]

Options:
  --repo PATH             Repository path; defaults to the current directory.
  --python-version X.Y    Shared Python ABI; defaults to 3.14.
  --source-venv PATH      Existing venv used to build a compatibility snapshot.
  --scope VALUE           Python entry scope: root, sandbox, or all (default).
  -h, --help              Show this help.
EOF
}

write_toolchain_inventory() {
  local repo_root="$1"
  local target_venv="$2"
  local python_version="$3"
  local state_path="$repo_root/.agents/runtime/state/toolchains.lock"
  local temp_path

  temp_path="$(mktemp "${state_path}.tmp.XXXXXX")"
  {
    printf '# Generated by manage-shared-dev-environment.\n'
    printf 'generated_at=%s\n' "$(date --iso-8601=seconds)"
    printf 'repository=%s\n' "$repo_root"
    python_print_inventory "$target_venv" "$python_version"
    node_print_inventory
    rust_print_inventory
  } > "$temp_path"
  mv -- "$temp_path" "$state_path"
  runtime_log "Wrote toolchain inventory: $state_path"
}

inspect_runtime() {
  local repo_root="$1"
  local target_venv="$2"
  local python_version="$3"

  printf 'repository=%s\n' "$repo_root"
  printf 'runtime.root=%s\n' "$repo_root/.agents/runtime"
  python_print_inventory "$target_venv" "$python_version"
  printf 'python.root_entry=%s\n' "$(readlink -f "$repo_root/.venv" 2>/dev/null || printf 'missing')"
  printf 'python.sandbox_entry=%s\n' "$(readlink -f "$repo_root/.agents/sandbox/.venv" 2>/dev/null || printf 'missing')"
  node_print_inventory
  rust_print_inventory
}

command_name="${1:-}"
[[ -n "$command_name" ]] || {
  usage
  exit 2
}
shift

repo_request="."
python_version="${MANAGED_PYTHON_VERSION:-3.14}"
source_venv=""
scope="all"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      [[ $# -ge 2 ]] || runtime_die "--repo requires a path"
      repo_request="$2"
      shift 2
      ;;
    --python-version)
      [[ $# -ge 2 ]] || runtime_die "--python-version requires X.Y"
      python_version="$2"
      shift 2
      ;;
    --source-venv)
      [[ $# -ge 2 ]] || runtime_die "--source-venv requires a path"
      source_venv="$2"
      shift 2
      ;;
    --scope)
      [[ $# -ge 2 ]] || runtime_die "--scope requires root, sandbox, or all"
      scope="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      runtime_die "Unknown option: $1"
      ;;
  esac
done

repo_root="$(runtime_resolve_repo "$repo_request")"
[[ "$python_version" =~ ^[0-9]+\.[0-9]+$ ]] || {
  runtime_die "Python version must use the major.minor form, for example 3.14"
}
target_venv="$(python_runtime_target "$repo_root" "$python_version")"
if [[ -z "$source_venv" ]]; then
  source_venv="$repo_root/.venv"
elif [[ "$source_venv" != /* ]]; then
  source_venv="$(realpath -m -- "$repo_root/$source_venv")"
fi

case "$command_name" in
  inspect)
    inspect_runtime "$repo_root" "$target_venv" "$python_version"
    ;;
  init)
    runtime_ensure_layout "$repo_root"
    requirements_lock="$repo_root/.agents/runtime/state/python-${python_version}-requirements.lock"

    source_real="$(readlink -f -- "$source_venv" 2>/dev/null || true)"
    target_real="$(readlink -f -- "$target_venv" 2>/dev/null || true)"
    if [[ -x "$source_venv/bin/python" && "$source_real" != "$target_real" ]]; then
      python_snapshot_requirements "$source_venv" "$requirements_lock"
    fi

    python_ensure_environment "$target_venv" "$python_version"
    python_install_snapshot "$target_venv" "$requirements_lock"
    write_toolchain_inventory "$repo_root" "$target_venv" "$python_version"
    ;;
  attach-python)
    [[ -x "$target_venv/bin/python" ]] || {
      runtime_die "Initialize the shared Python environment before attaching entries: $target_venv"
    }
    runtime_ensure_layout "$repo_root"
    requirements_lock="$repo_root/.agents/runtime/state/python-${python_version}-requirements.lock"
    [[ -f "$repo_root/.agents/runtime/state/toolchains.lock" ]] || {
      runtime_die "Shared environment initialization did not complete; run init again"
    }
    # Reconcile the compatibility snapshot immediately before moving any old
    # entry. This prevents attachment to a partially initialized environment.
    python_install_snapshot "$target_venv" "$requirements_lock"
    "$target_venv/bin/python" -m pip check
    if python_scope_is_attached "$repo_root" "$target_venv" "$scope"; then
      runtime_log "Requested Python entries are already attached; no backup was created"
      write_toolchain_inventory "$repo_root" "$target_venv" "$python_version"
    else
      backup_root="$(runtime_allocate_backup_root "$repo_root")"
      {
        printf 'created_at=%s\n' "$(date --iso-8601=seconds)"
        printf 'target=%s\n' "$target_venv"
        printf 'scope=%s\n' "$scope"
        printf 'root_entry=%s\n' "$repo_root/.venv"
        printf 'sandbox_entry=%s\n' "$repo_root/.agents/sandbox/.venv"
      } > "$backup_root/backup-manifest.txt"
      python_attach_scope "$repo_root" "$target_venv" "$scope" "$backup_root"
      printf '%s\n' "$backup_root" > "$repo_root/.agents/runtime/state/last-backup"
      write_toolchain_inventory "$repo_root" "$target_venv" "$python_version"
      runtime_log "Backup root: $backup_root"
    fi
    ;;
  validate)
    python_validate_scope "$repo_root" "$target_venv" "$python_version" "$scope"
    node_status=0
    rust_status=0
    node_validate_toolchain || node_status=$?
    rust_validate_toolchain || rust_status=$?
    [[ -f "$repo_root/.agents/runtime/state/toolchains.lock" ]] || {
      runtime_die "Missing toolchain inventory; run init first"
    }
    if (( node_status != 0 || rust_status != 0 )); then
      runtime_warn "Shared Python is valid, but one or more optional language toolchains are missing"
    fi
    runtime_log "Shared development environment is valid"
    ;;
  *)
    usage
    runtime_die "Unknown command: $command_name"
    ;;
esac
